<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Rumahsakit;

class UnitKerjaFromExcelSeeder20251103010235 extends Seeder
{
    public function run(): void
    {
        $rows = array (
  0 => 
  array (
    'nama_rumahsakit' => 'Direktorat Angkutan Udara',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  1 => 
  array (
    'nama_rumahsakit' => 'Direktorat Bandar Udara',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  2 => 
  array (
    'nama_rumahsakit' => 'Direktorat Keamanan Penerbangan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  3 => 
  array (
    'nama_rumahsakit' => 'Direktorat Kelaikudaraan dan Pengoperasian Pesawat Udara',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  4 => 
  array (
    'nama_rumahsakit' => 'Direktorat Navigasi Penerbangan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  5 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas I Wilayah II',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 27,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  6 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas I Wilayah III',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 251,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  7 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas I Wilayah IV',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 411,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  8 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas I Wilayah V',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 381,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  9 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas II Wilayah VI',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 61,
    'latitude' => -0.7869,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  10 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas II Wilayah VII',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 322,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  11 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas II Wilayah VIII',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 343,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  12 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas II Wilayah IX',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 475,
    'latitude' => -0.8918,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  13 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas II Wilayah X',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 489,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  14 => 
  array (
    'nama_rumahsakit' => 'Kantor Otoritas Bandar Udara Kelas Utama Wilayah I',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 272,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  15 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Aji Pangeran Tumenggung Pranoto',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 324,
    'latitude' => -0.4849,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  16 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Budiarto',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 272,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  17 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Djalaluddin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 350,
    'latitude' => 0.6373,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  18 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Domine Eduard Osok',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 485,
    'latitude' => -0.926,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  19 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I H. As. Hanandjoeddin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 145,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  20 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Haluoleo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 404,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  21 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Kalimarau',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 315,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  22 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Mopah',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 489,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  23 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Mutiara SIS Al Jufri',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 363,
    'latitude' => -0.918,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  24 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Utama Juwata',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 329,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  25 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas I Wamena',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 498,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  26 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Binaka',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 50,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  27 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Cut Nyak Dhien',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 15,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  28 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Douw Aturure',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 495,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  29 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Fransiskus Xaverius Seda',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 444,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  30 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Gusti Sjamsir Alam',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 308,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  31 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II H. Asan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 295,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  32 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II H. Hasan Aroeboesman',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 432,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  33 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Iskandar',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 294,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  34 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Karel Sadsuitubun',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 457,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  35 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Kasiguncu',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 359,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  36 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Komodo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 438,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  37 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Lede Kalumbang',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 367,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  38 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Mozes Kilangin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 493,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  39 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Nop Goliat Dekai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 504,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  40 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Pangsuma',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 275,
    'latitude' => 0.833,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  41 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Rahadi Oesman',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 277,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  42 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Rendani - Manokwari',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 475,
    'latitude' => -0.8918,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  43 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Sultan Babullah',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 471,
    'latitude' => 0.8314,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  44 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Sultan Muhammad Salahuddin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 428,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  45 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Syukuran Aminuddin Amir',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 351,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  46 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Tampa Padang',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 366,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  47 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Tebelian',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 285,
    'latitude' => 0.063,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  48 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas II Umbu Mehang Kunda',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 448,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  49 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III A.A Bere Tallo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 431,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  50 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Aek Godang',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 40,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  51 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Akimuga',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 493,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  52 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Amahai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 456,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  53 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Andi Jemma',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 380,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  54 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Arung Palakka',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 372,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  55 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Ayawasi',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 480,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  56 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Babo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 478,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  57 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Bandaneira',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 456,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  58 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Batom',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 502,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  59 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Betoambari',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 409,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  60 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Bilorai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 492,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  61 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Bintuni',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 478,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  62 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Bokondini',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 503,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  63 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Bomakia',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 487,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  64 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Buli',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 465,
    'latitude' => 0.609,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  65 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Cakrabhuwana',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 184,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  66 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Dabo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 151,
    'latitude' => -0.4793,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  67 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Datah Dawai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 319,
    'latitude' => 0.617,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  68 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III David Constantijn Saudale',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 442,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  69 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Depati Parbo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 90,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  70 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Dewa Daru',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 197,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  71 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Dobo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 454,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  72 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Dr. Ferdinand Lumbantobing',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 46,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  73 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Elelim',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 505,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  74 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Emalamo Sanana',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 468,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  75 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Enarotali',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 495,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  76 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Ewer',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 486,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  77 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Frans Sales Lega',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 437,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  78 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Gamar Malamo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 467,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  79 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Gewayantana',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 433,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  80 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III H. Aroepala',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 377,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  81 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Haji Muhammad Sidik',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 290,
    'latitude' => -0.943,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  82 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Harun Thohir',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 233,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  83 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Ilaga',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 496,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  84 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Illu',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 497,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  85 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Inanwatan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 483,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  86 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Japura',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 78,
    'latitude' => -0.354,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  87 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III John Becker',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 504,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  88 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kambuaya',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 480,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  89 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kamur',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 486,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  90 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Karubaga',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 503,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  91 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kebar',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 484,
    'latitude' => -0.925,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  92 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kepi',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 488,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  93 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kimam',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 489,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  94 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kiwirok',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 502,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  95 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kokonau',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 493,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  96 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kol. Robert Atty Bessing',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 326,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  97 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kuabang',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 467,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  98 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kuala Kurun',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 291,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  99 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Kuala Pembuang',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 299,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  100 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Lagaligo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 378,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  101 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Larat',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 460,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  102 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Lasikin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 18,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  103 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Lasondre',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 37,
    'latitude' => -0.578,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  104 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Letung - Anambas',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 150,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  105 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Long Apung',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 326,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  106 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Maimun Saleh',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 22,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  107 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Mali',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 430,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  108 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Malikussaleh',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 11,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  109 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Mararena',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 511,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  110 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Maratua',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 315,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  111 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Marinda',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 481,
    'latitude' => -0.423,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  112 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Matahora',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 408,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  113 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Mathilda Batlayeri',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 460,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  114 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Melak',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 316,
    'latitude' => -0.256,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  115 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Melonguane',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 336,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  116 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Mentawai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 59,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  117 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Merdey',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 478,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  118 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Moanamani',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 491,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  119 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Morowali',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 356,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  120 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Muara Bungo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 89,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  121 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Muko-Muko',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 122,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  122 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Mulia',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 497,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  123 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Naha',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 334,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  124 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Namniwel',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 456,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  125 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Namrole',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 453,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  126 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Nangapinoh',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 280,
    'latitude' => -0.609,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  127 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Numfor',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 506,
    'latitude' => -0.978,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  128 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Nunukan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 327,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  129 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Oesman Sadik',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 466,
    'latitude' => -0.637,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  130 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Okaba',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 489,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  131 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Oksibil',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 502,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  132 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Pitu',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 469,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  133 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Pogogul',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 354,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  134 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Raja Haji Abdullah',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 149,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  135 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Rampi',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 380,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  136 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Ranai, Natuna',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 152,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  137 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Rembele',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 12,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  138 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Sanggu',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 288,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  139 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Sangia Nibandera',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 399,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  140 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Seko',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 380,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  141 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Senggeh',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 508,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  142 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Siboru',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 473,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  143 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Silampari',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 112,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  144 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Soa',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 441,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  145 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Stevanus Rumbewas',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 509,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  146 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Sugimanuru',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 406,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  147 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Sultan Bantilan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 362,
    'latitude' => 0.922,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  148 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Sultan Muhammad Kaharuddin',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 426,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  149 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tanah Merah',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 487,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  150 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tanjung Api',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 361,
    'latitude' => -0.842,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  151 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tanjung Harapan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 325,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  152 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tardamu',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 443,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  153 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Teminabuan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 483,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  154 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Teuku Cut Ali',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 5,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  155 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tiom',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 499,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  156 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Toraja',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 388,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  157 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Trunojoyo',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 253,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  158 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tuanku Tambusai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 84,
    'latitude' => 0.386,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  159 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tumbang Samba',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 293,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  160 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Tunggul Wulung',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 194,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  161 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Utarom',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 474,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  162 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Waghete',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 490,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  163 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Wahai',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 456,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  164 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Wasior',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 479,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  165 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Wunopito',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 435,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  166 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Kelas III Yuvai Semaring',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 327,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  167 => 
  array (
    'nama_rumahsakit' => 'Kantor Unit Penyelenggara Bandar Udara Khusus Ibu Kota Nusantara',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 321,
    'latitude' => -0.502,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  168 => 
  array (
    'nama_rumahsakit' => 'Penugasan',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 156,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  169 => 
  array (
    'nama_rumahsakit' => 'Perum LPPNPI/Airnav',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 272,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
  170 => 
  array (
    'nama_rumahsakit' => 'Politeknik Penerbangan Indonesia Curug',
    'alamat' => NULL,
    'no_telp' => NULL,
    'regency_id' => 272,
    'latitude' => NULL,
    'longitude' => NULL,
    'matra' => 'Udara',
    'instansi' => 'Pusat',
    'created_at' => '2025-11-03 01:02:35',
    'updated_at' => '2025-11-03 01:02:35',
  ),
);

        // Upsert idempotent berdasarkan kombinasi (nama_rumahsakit, regency_id)
        foreach (array_chunk($rows, 500) as $chunk) {
            foreach ($chunk as $row) {
                Rumahsakit::updateOrCreate(
                    [
                        'nama_rumahsakit' => $row['nama_rumahsakit'],
                        'regency_id'      => $row['regency_id'],
                    ],
                    $row
                );
            }
        }
    }
}
